package com.neueda.leap.repository.impl;

import com.neueda.leap.Holdings;
import com.neueda.leap.repository.HoldingsRepository;
import com.neueda.leap.mapper.HoldingsMapper;
import org.springframework.stereotype.Repository;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * MyBatis-based implementation of HoldingsRepository
 */
@Repository
public class HoldingsRepositoryImpl implements HoldingsRepository {

    private final HoldingsMapper holdingsMapper;

    public HoldingsRepositoryImpl(HoldingsMapper holdingsMapper) {
        this.holdingsMapper = holdingsMapper;
    }

    @Override
    public Optional<Holdings> findById(UUID holdingId) {
        Holdings holdings = holdingsMapper.selectHoldingById(holdingId);
        return Optional.ofNullable(holdings);
    }

    @Override
    public Optional<Holdings> findByAccountIdAndInstrumentId(UUID accountId, UUID instrumentId) {
        Holdings holdings = holdingsMapper.selectHoldingByAccountAndInstrument(accountId, instrumentId);
        return Optional.ofNullable(holdings);
    }

    @Override
    public List<Holdings> findByAccountId(UUID accountId, int limit, int offset) {
        return holdingsMapper.selectHoldingsByAccountId(accountId, limit, offset);
    }

    @Override
    public int countByAccountId(UUID accountId) {
        return holdingsMapper.countHoldingsByAccountId(accountId);
    }

    @Override
    public List<Holdings> findByInstrumentId(UUID instrumentId, int limit, int offset) {
        return holdingsMapper.selectHoldingsByInstrumentId(instrumentId, limit, offset);
    }

    @Override
    public int countByInstrumentId(UUID instrumentId) {
        return holdingsMapper.countHoldingsByInstrumentId(instrumentId);
    }

    @Override
    public Holdings save(Holdings holdings) {
        // Check if holding already exists
        Optional<Holdings> existing = findByAccountIdAndInstrumentId(holdings.getAccountId(), holdings.getInstrumentId());
        
        if (existing.isPresent()) {
            // Update existing holding
            holdingsMapper.updateHolding(holdings.getAccountId(), holdings.getInstrumentId(), holdings.getQuantity());
            // Return the updated holding with existing ID
            holdings.setHoldingId(existing.get().getHoldingId());
        } else {
            // Insert new holding
            holdingsMapper.insertHolding(holdings.getAccountId(), holdings.getInstrumentId(), holdings.getQuantity());
            // Note: The ID is generated by the database via gen_random_uuid()
            // For now, we'll need to re-fetch to get it, or rely on the caller to set it
            // In a production system, you might use RETURNING clause or other mechanisms
        }
        
        return holdings;
    }

    @Override
    public boolean deleteById(UUID holdingId) {
        Optional<Holdings> existing = findById(holdingId);
        if (existing.isPresent()) {
            holdingsMapper.deleteHolding(holdingId);
            return true;
        }
        return false;
    }
}
